### ISSUE TITLE
'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by karankrish** [HackerEarth-Challenges/ML-Challenge-3#1]
np.random.choice(train.index.values, 1e6) : for this line of code error is showing in CatBoost_Starter.ipynb

**Comment by saraswatmks** [comment]
Hi @karankrish  I did not face any such error. 

Alternatively, you can try doing:

import random
rows = random.sample(train.index, 1e6)
train = train.iloc[rows]

or 

train = train.sample(n = 1e6)  #simpler

**Comment by bharadwaj6** [comment]
@karankrish Faced same issue. Change it to `np.random.choice(train.index.values, int(1e6))` or just put the integer yourself... that should work. 

Alternatively, older versions of numpy seem to work with existing code (like 1.11). Check for yourself...
