### ISSUE TITLE
Three issues in Keras starter code

### ISSUE THREAD

**Issue by Anirudhsekar96** [HackerEarth-Challenges/ML-Challenge-3#2]
1. The predicted Probability should have column 1 instead of 0 for correct prediction
2. roc_auc_score needs to be imported from sklearn library (sklearn.metrics)
3. some machines may not accept 1e6 directly (cannot accept float), and it needs to be typecasted as int(1e6)

**Comment by saraswatmks** [comment]
@Anirudhsekar96 Thank you for spotting them. I've made the corrections.
